/* EXERCICIO SQL 2 */
/* CRIANDO A TABELA DE ALUNOS PARA ARMAZENAR OS DADOS */
/* A COLUNA ID VAI SER A CHAVE PRIMARIA, E VOU USAR AUTO_INCREMENT PARA O BANCO DE DADOS SE ENCARREGAR
 DE CRIAR OS ID'S NECESSÁRIOS, USAMOS TINYINT NA IDADE VISTO QUE NINGUEM TEM MAIS QUE 100 ANOS*/
CREATE TABLE ALUNOS (ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, NOME VARCHAR(30), EMAIL VARCHAR(30), IDADE TINYINT);

/* POPULANDO A TABELA DE ALUNOS */
/* COMO A COLUNA ID É AUTO_INCREMENTE ENTÃO NÃO PRECISO ESPECIFICAR ELA NO INSERT*/
INSERT INTO ALUNOS (NOME, EMAIL, IDADE) VALUES ('LUCAS', 'LUCAS@ZUP.COM.BR', 29);
INSERT INTO ALUNOS (NOME, EMAIL, IDADE) VALUES ('JOAO', 'JOAO@ZUP.COM.BR', 40);
INSERT INTO ALUNOS (NOME, EMAIL, IDADE) VALUES ('MARIA', 'MARIA@GMAIL.COM.BR', 15);
INSERT INTO ALUNOS (NOME, EMAIL, IDADE) VALUES ('THIAGO', 'THIAGO@YAHOO.COM.BR', 22);

/* CRIANDO A TABELA DE AVALIACOES */
/* A COLUNA ID VAI SER A CHAVE PRIMARIA, E VOU USAR AUTO_INCREMENT PARA O BANCO DE DADOS SE ENCARREGAR
 DE CRIAR OS ID'S NECESSÁRIOS, O TITULO TEM UM TAMANHO DE 30 CARACTERES, CRIADO UMA COLUNA CHAMADA RESPOSTA_CORRETA, VAI SER NELA QUE VAI CONTER A RESPOSTA A SER COMPARADA*/
CREATE TABLE AVALIACAO (ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, TITULO VARCHAR(30), DESCRICAO VARCHAR(255), RESPOSTA_CORRETA TEXT(8000));

/* POPULANDO A TABELA DE AVALIACOES*/
/* COMO A COLUNA ID É AUTO_INCREMENTE ENTÃO NÃO PRECISO ESPECIFICAR ELA NO INSERT */
INSERT INTO AVALIACAO (TITULO, DESCRICAO, RESPOSTA_CORRETA) VALUES ('SQL', 'MONTE UM SELECT EM SQL', 'SELECT * FROM ALUNOS');
INSERT INTO AVALIACAO (TITULO, DESCRICAO, RESPOSTA_CORRETA) VALUES ('JPA', 'MONTE UM SELECT EM JPQL', 'SELECT A FROM ALUNO A');
INSERT INTO AVALIACAO (TITULO, DESCRICAO, RESPOSTA_CORRETA) VALUES ('SPRING', 'CONSTRUA UMA API EM SPRING', 'LOREM IPSUM');

/* CRIANDO A TABELA DE RESPOSTA */
/* ESSA TABELA VAI CONTER AS RESPOSTAS DOS ALUNOS AS AVALIACOES, VAI EXISTIR OS CAMPOS ID_ALUNO COMO CHAVE ESTRANGEIRA
E TAMBEM ID_AVALIACAO COMO CHAVE ESTRANGEIRA, ESSES CAMPOS NAO PODEM SER NULOS. COMO USAMOS CHAVE ESTRANGEIRA, É NECESSÁRIO CRIARMOS UM ÍNDICE
ISSO OTIMIZA A INDEXAÇÃO DO BANCO DE DADOS A RESPOSTA DO ALUNO VAI SER ARMAZENADA NA COLUNA RESPOSTA_ALUNO */
CREATE TABLE RESPOSTA (ID INT NOT NULL AUTO_INCREMENT, ID_ALUNO INT NOT NULL, ID_AVALIACAO INT NOT NULL, RESPOSTA_ALUNO TEXT(8000), PRIMARY KEY (ID), INDEX ALUNO_FK_idx ( ID_ALUNO ASC),
  INDEX AVALIACAO_FK_idx (ID_AVALIACAO ASC),  CONSTRAINT ALUNO_FK FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS (ID),  CONSTRAINT AVALIACAO_FK FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO (ID));

/* CRIANDO A TABELA CORRECAO */
/* ESSA TABELA VAI CONTER A CORRECAO DA AVALIACAO DOS NOSSOS ALUNOS, TEREMOS UMA COLUNA ID COM AUTO_INCREMENT, UMA CHAVE ESTRANGEIRA
QUE SERÁ O ID_RESPOSTA, MAIS UMA COLUNA COM A NOTA DO ALUNO DE TIPO TINYINT
*/
CREATE TABLE CORRECAO (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, ID_RESPOSTA INT NOT NULL, NOTA TINYINT, INDEX AVALICAO_FK_idx (ID_RESPOSTA ASC), CONSTRAINT RESPOSTA_FK FOREIGN KEY (ID_RESPOSTA)
REFERENCES RESPOSTA(ID));

/* ALUNOS QUE RESPONDERAM UMA AVALIACAO ESPECIFICA 
RELACIONAMOS 3 TABELAS, TODAS COM SEUS RESPECTIVOS ID'S, DESSA MANEIRA TROUXEMOS TODAS AS INFORMAÇÕES NECESSÁRIAS */
SELECT * FROM RESPOSTA R INNER JOIN AVALIACAO A ON R.ID_AVALIACAO = A.ID INNER JOIN ALUNOS AL ON R.ID_ALUNO = AL.ID;

/* QUANTIDADE DE RESPOSTAS POR AVALIAÇÃO
AQUI REALIZAMOS O COUNT AGRUPANDO PELA AVALIACAO, PARA TERMOS ESSE RETORNO */
SELECT A.TITULO, COUNT(*)  AS QTD_RESPOSTAS FROM RESPOSTA R INNER JOIN AVALIACAO A ON R.ID_AVALIACAO = A.ID 
GROUP BY A.TITULO;

/* NOTA MÉDIA DA AUTOCORREÇÃO POR AVALIAÇÃO 
MAIS UMA VEZ, REALIZAMOS UM INNER JOIN ENTRE 3 TABELAS, POIS CADA UMA TEM SUA RESPONSABILIDADE ESPECIFICA ENTÃO AGRUPOS PELO TITULO E USAMOS A FUNCAO AVG, PARA TRAZER A MEDIA
*/
SELECT A.TITULO, AVG(C.NOTA) AS MEDIA_NOTA FROM CORRECAO C INNER JOIN RESPOSTA R ON C.ID_RESPOSTA = R.ID INNER JOIN AVALIACAO A ON R.ID_AVALIACAO = A.ID
GROUP BY A.TITULO;

/* UMA OUTRA SOLUCAO SERIA COLOCAR A CORRECAO COMO UMA COLUNA NA RESPOSTA, RESPONDI DESSA MANEIRA, POIS ACHEI QUE ERA A PROPOSTA DO EXERCICIO*/

 