version: '3'
services:
    bcb:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
        ports: 
            - 8082:8082
    erp-itau:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
        ports: 
            - 9091:9091
    postgres:
        image: 'postgres:alpine'
        volumes:
        - postgres-volume:/var/lib/postgresql/data
        ports:
          - 5432:5432
        environment:
          POSTGRES_USER: pix
          POSTGRES_PASSWORD: password
          POSTGRES_DB: keymanager
          POSTGRES_HOST: postgres

    keymanager-grpc:
      image: 'lucas/keymanager-grpc'
      ports:
      - 50051:50051
      environment:
        JDBC_URL: jdbc:postgresql://postgres:5432/keymanager
        API_ITAU: http://erp-itau:9091
        API_BCB: http://bcb:8082
      depends_on:
        - postgres
 
volumes:
    postgres-volume: