/* EXERCICIO SQL */
/* CRIANDO A TABELA DE ALUNOS PARA ARMAZENAR OS DADOS */
/* A COLUNA ID VAI SER A CHAVE PRIMARIA, E VOU USAR AUTO_INCREMENT PARA O BANCO DE DADOS SE ENCARREGAR
 DE CRIAR OS ID'S NECESSÁRIOS */
CREATE TABLE ALUNOS (ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, NOME VARCHAR(30), EMAIL VARCHAR(30), IDADE TINYINT);

/* POPULANDO A TABELA DE ALUNOS */
/* COMO A COLUNA ID É AUTO_INCREMENTE ENTÃO NÃO PRECISO ESPECIFICAR ELA NO INSERT*/
INSERT INTO ALUNOS (NOME, EMAIL, IDADE) VALUES ('LUCAS', 'LUCAS@ZUP.COM.BR', 29);
INSERT INTO ALUNOS (NOME, EMAIL, IDADE) VALUES ('JOAO', 'JOAO@ZUP.COM.BR', 40);
INSERT INTO ALUNOS (NOME, EMAIL, IDADE) VALUES ('MARIA', 'MARIA@GMAIL.COM.BR', 15);
INSERT INTO ALUNOS (NOME, EMAIL, IDADE) VALUES ('THIAGO', 'THIAGO@YAHOO.COM.BR', 22);

/* LISTANDO TODO OS ALUNOS */
SELECT * FROM ALUNOS;

/* DELETANDO UM REGISTRO POR EMAIL */
DELETE FROM ALUNOS WHERE EMAIL = 'JOAO@ZUP.COM.BR';

/* BUSCANDO TODOS OS ALUNOS QUE CONTEM "ZUP" NO EMAIL */
SELECT * FROM ALUNOS WHERE EMAIL LIKE '%ZUP%';

/* LISTANDO ALUNOS ORDENANDO PELA IDADE EM ORDEM CRESCENTE*/
SELECT * FROM ALUNOS ORDER BY IDADE ASC;
