version: 0.2

phases:
  install:
    commands:
      - curl -o /bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - wget -qO- https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz | tar xvz
      - mv linux-amd64/helm /bin/helm
      - chmod +x /bin/kubectl /bin/helm ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli

  pre_build:
    commands:
      - echo connecting ecr
      - docker login -u AWS -p $(aws ecr-public get-login-password --region us-east-1) $URL_REPO
      - sh gradlew build
      - echo exporting kubeconfig
      - export KUBECONFIG=$HOME/.kube/config
      
  build:
    commands:
#      - IMAGE_REPO_NAME="$DEPLOYMENT_NAME"
#      - AWS_ACCOUNT_ID="$ACCOUNT_ID"
#      - AWS_DEFAULT_REGION="$DEFAULT_REGION"
#      - IMAGE_TAG="$IMAGE_TAG"
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker image ls
      - docker build -t $DEPLOYMENT_NAME . 
      - docker tag $DEPLOYMENT_NAME:$IMAGE_TAG $URL_REPO/$DEPLOYMENT_NAME:$IMAGE_TAG
      - docker image ls
      - echo Build completed on `date`  

  post_build:
    commands:
      - echo Pushing in to Amazon ECR...
      - docker push $URL_REPO/$DEPLOYMENT_NAME:$IMAGE_TAG
      - echo Push completed on `date`  
      - echo deploying to cluster...
      - helm version --short
      - helm lint pipeline/helm/$DEPLOYMENT_NAME --values pipeline/helm/$DEPLOYMENT_NAME/values.yaml
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --role-arn $ARN_ROLE
      - kubectl get nodes
      - helm upgrade -i $DEPLOYMENT_NAME pipeline/helm/$DEPLOYMENT_NAME/ --values pipeline/helm/$DEPLOYMENT_NAME/values.yaml