{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orange-talents-05-template-pix-keymanager-grpc.serviceAccountName" . }}
  labels:
    {{- include "orange-talents-05-template-pix-keymanager-grpc.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
